version: '3'
services:
  web:
    image: fermope/dev_ops_web
    build: .
    environment:
      MYENV: EXAMPLE
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
    volumes:
      - .:/usr/src/app
    command: 
      - /bin/sh
      - -c
      - | 
        python manage.py migrate
        python manage.py createsuperuser --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} --skip-checks --noinput
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"